db:
  image: postgres
  environment:
    - POSTGRES_DB=fossology
    - POSTGRES_USER=fossy
    - POSTGRES_PASSWORD=fossy
web:
  build: .
  command: bash -c "/usr/local/lib/fossology/fo-postinstall && /usr/sbin/apache2ctl -D FOREGROUND"
  ports:
    - 80:80
  links:
    - db
